<?php
    $_products = $this->getProductCollection();
    $w = 65;
    $h = 65;
    
    $config = new EM_Em0059settings_Em0059settings();
    $w = $config->get_lastest_review_width();
    $h = $config->get_lastest_review_height();
    $bg = $config->get_lastest_review_bgcolor(); 
    
?>
<div class="lasted-review">
    <div class="block-title">
        <strong><span>Latest Reviews</span></strong>
    </div>
    <?php if (count($_products) == 0): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div class="lastest-review-content">        
        <div class="product-shop">
            <ol class="products-list">
            <?php $i=0; foreach ($_products->getItems() as $_product): ?>
                <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                    <a href="<?php echo $this->getUrl().$_product->getUrlPath() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w, $h) ?>" width="<?php echo $w ?>" height="<?php echo $h ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-shop">
                        <div class="f-fix">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>                            
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
        </div>
    </div>
    <?php endif; ?>
</div>