<?php
/**
 * FAQs And Product Questions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FAQs And Product Questions
 * @author     Asif Hussain <support@fmeextensions.com>
 * 	       
 * @copyright  Copyright 2012 © www.fmeextensions.com All right reserved
 */

?>

<?php  $faq_product = $this->getProduct(); ?>

<p class="ask-question">
	
	<?php
		$url = '#';
		if(Mage::getStoreConfig('prodfaqs/product_page/show_faqs_on') == 'new_page'):
			$url = Mage::helper('prodfaqs')->getProductFaqsPageUrl($faq_product);
		else:
			$url = "#product-faq-section";
		endif;
		
	?>
	
	
	<a href="<?php echo $url; ?>">
		<?php if(Mage::helper('prodfaqs')->isProductFaqsAskQuestionEnable() && (Mage::getStoreConfig('prodfaqs/product_ask/allow_customers') == 'all' || (Mage::getStoreConfig('prodfaqs/product_ask/allow_customers') == 'registered' && Mage::helper('customer')->isLoggedIn()))): ?>	
			<?php echo $this->__('Ask a question ').$this->__('('.$this->countFaqsofProduct($faq_product).')') ?>
		<?php else: ?>
			<?php echo $this->__('View Questions ').$this->__('('.$this->countFaqsofProduct($faq_product).')') ?>
		<?php endif; ?>
	</a>
</p>

