<?php
/**
 * FAQs And Product Questions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FAQs And Product Questions
 * @author     Asif Hussain <support@fmeextensions.com>
 * 	       
 * @copyright  Copyright 2012 © www.fmeextensions.com All right reserved
 */
?>



<?php if(Mage::getStoreConfig('prodfaqs/general/faq_search_block')): ?>

<div class="block em_blog-cat">
	
        <div class="block-title">
   
		<strong><?php echo $this->__('Search Information'); ?></strong>
	</div>
	
	<div class="search-content">
            <form action="<?php echo Mage::helper('prodfaqs')->getUrl('search') ?>" id="faqsForm" method="post" >
            <fieldset class="faqs">
            
           <table cellspacing="0" cellpadding="0" border="0">
             <tbody>  
                <tr>
                	<td class="faq-search"><?php echo Mage::helper('prodfaqs')->__('Enter a Keyword to Search for:') ?></td>
                </tr>
                <tr>
                	<td class="value"><input id="faqssearch" name="faqssearch" value="" class="required-entry required-entry input-text" type="text"/></td>
                </tr>
                <tr>
                	<td style="text-align:right; padding-top:5px">
                  		<button class="form-button" type="submit"><span><?php echo Mage::helper('prodfaqs')->__('Search') ?></span></button>
                	</td>
                </tr> 
             </tbody>
           </table>
            </fieldset>
           </form>
        </div>
</div>	

<?php endif; ?>


<?php  

$maxDisplay  =  Mage::getStoreConfig('prodfaqs/general/faq_maxtopic');
$collection = $this->getItems($maxDisplay);
$counter=0;

?>



<?php if(Mage::getStoreConfig('prodfaqs/general/faq_block')): ?>

<div class="block block-faqs" style="display:inline-block !important">
        <div class="block-title">
		<strong><?php echo $this->__('Information Guides'); ?></strong>
	</div> 
 
	<?php if ( count($collection) == 0 ) : ?>  
	    <div class="block-content">
		<p class="empty"><?php echo Mage::helper('prodfaqs')->__('No Faqs find yet!') ?></p>
	    </div>
	<?php else : ?>
	    <div class="menu" style="height:auto !important; width:180px;">
		<strong><?php echo Mage::helper('prodfaqs')->__('Choose A Topic:') ?></strong>
		<ul>
		 <?php foreach ($collection as $_topic): ?>
			<li><a href="<?php echo Mage::helper('prodfaqs')->getUrl($_topic['identifier']); ?>"><?php echo $_topic["title"]; ?></a></li>
		    <?php $counter++; ?>   
		 <?php endforeach; ?>
		 
		 <li><a href="<?php echo Mage::helper('prodfaqs')->getUrl(); ?>"><?php echo Mage::helper('prodfaqs')->__('Ask Us a Question ?') ?></a></li>
	       </ul>         
	    </div>
	    
	<?php endif; ?>   

</div>

<?php endif; ?>	

