<?php
/**
 * FAQs And Product Questions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FAQs And Product Questions
 * @author     Asif Hussain <support@fmeextensions.com>
 * 	       
 * @copyright  Copyright 2012 © www.fmeextensions.com All right reserved
 */
?>
<?php

$faqs = $this->getProductNextPageFaqs();

$num_of_faqs = count($faqs);

$allowed_rating_customers = Mage::helper('prodfaqs')->getProductFaqsRatingCustomers();

//Faqs that already has been rated, in that session
$faqs_already_rated = Mage::getSingleton('customer/session')->getRatedFaqsId();


?>

<?php if(Mage::helper('prodfaqs')->isProductFaqsRatingEnable()) : ?>

	<script type="text/javascript">
	
		Event.observe(window, 'load', function() {
			
			var faq = '<?= $num_of_faqs; ?>';
			//var is_rated = '<?= $is_rated; ?>';
			
			
				for(f=1; f<=faq; f++){
					
					var rating_element = $('rating_'+f);
					if($('has_rated_'+f) != undefined){
						var is_rated = $('has_rated_'+f).readAttribute('title');
						if(is_rated == 'yes') is_rated = true;
						else if(is_rated == 'no') is_rated = false;
					}
					if(rating_element != undefined){
						
							rating = new Control.Rating(rating_element,
									{
										rated: is_rated,
										value: parseFloat($('stars_'+f).readAttribute('title')),
										faq_id: parseInt($('faq_id_'+f).readAttribute('title')),
										updateUrl:'<?php echo $this->getUrl('*/*/rating') ?>',
										updateOptions : {
											method: 'post',
											onSuccess: function(transport) {
												$('rating-success').appear();
												$('rating_message').update(transport.responseText);												
												},
											onFailure: function(transport) {
												$('rating-fail').appear();
												$('rating_message').update(transport.responseText);
												}
											}
									});
					}			
				}			
		});
	</script>

<?php endif; ?>


<?php

// like/unlike
$t_session = Mage::getSingleton('customer/session');
if($t_session->isLoggedIn()){
    
    $customer = $t_session->getCustomer();
    $customer_name = $customer->getFirstname();
    $customer_email = $customer->getEmail();
    $customer_id = $customer->getId();
    
    $customer_thumb_path = $this->getJsUrl('prodfaqs/like/dman.png'); 
    $customer_thumb = "<img src='$customer_thumb_path' style='width:15px; height:15px; margin:0 5px;'>";

}

?>

<?php if(Mage::helper('customer')->isLoggedIn() && Mage::helper('prodfaqs')->isProductFaqLikeEnable()): ?>

<script type="text/javascript">
	
    Event.observe(window, 'load', function() {
		
		var total_faqs = '<?= $num_of_faqs; ?>';
		var customer_name = '<?= $customer_name; ?>';
		var customer_id = '<?= $customer_id; ?>';
		
		for(f=1; f<=total_faqs; f++){
		    
		    if($('like_faq_id_'+f) != undefined){
			
			like = new Control.Like($('like_container_'+f),$('like_element_'+f),$('like_result_'+f),$('likeby_text_'+f),$('count_elements_'+f),
				{
				    likeby_name		: customer_name,
				    likeby_id 		: customer_id,
				    liked_obj_id 	: parseInt($('like_faq_id_'+f).readAttribute('title')),
				    likeby_avatar 	: '<?php echo $customer_thumb_path; ?>',
				    updateUrl		:'<?php echo $this->getUrl('prodfaqs/index/like') ?>',
				    updateOptions 	: {					
							    method:'post',
							    onSuccess: function(transport) {}
							   }
				    
				});
			
		    }
		    
		}
	
    });

</script>

<?php endif; ?>




<!--Reply JS STARTS-->

<?php if(Mage::helper('customer')->isLoggedIn() && Mage::getStoreConfig('prodfaqs/product_page/reply')): ?>

<script type="text/javascript">	
    
	function showJsCommentForm(formWraperId,testimonial_id){		
		
		if(testimonial_id != null){
			
			if(formWraperId == null){ 
				var reply_text = $('thread-customer-reply-text-'+testimonial_id);//this is for thread form
			}else{
				var reply_text = $('customer-reply-text-'+testimonial_id);
			}
			
				
			if(formWraperId == null){ //this is for thread form
				formWraperId = 'thread-js-plugin-reply-form-wraper'+testimonial_id;
				
				//cenecel button hide, for thread
				$('thread-js-plugin-reply-form-cancel'+testimonial_id).observe('click',function(event){
					
						formWraperId.hide();
					
					});
			}
			
			formWraperId = $(formWraperId);
			
			reply_text.update("<?php echo __("What's on your mind") ?>");
			
			reply_text.observe('focus',function(event){
				
				if(reply_text.getValue() == "<?php echo __("What's on your mind") ?>"){
					reply_text.update("");
				}
				
			});
			
			reply_text.observe('blur',function(event){
				
				if(reply_text.getValue() == ""){
					reply_text.update("<?php echo __("What's on your mind") ?>");
				}
				
			});
		}
		
		formWraperId.show();
		
	}
	
	
	
	function submitAjaxCommentReply(parent_id){
		
		//form validation 
		if($('customer-reply-text-'+parent_id).getValue() == '' || $('customer-reply-text-'+parent_id).getValue() == "What's on your mind"){
			
			alert('<?php echo __('The comment field is required') ?>');
			return false;
		}
		
		var url = '<?php echo $this->getUrl('prodfaqs/index/commentreply') ?>';
		
		new Ajax.Request(url, {
				
				method		: 'post',
				parameters	: {
							parent_faq_id	: parent_id,
							reply_comments		: $('customer-reply-text-'+parent_id).getValue(),
							customer_name		: '<?php echo $customer_name; ?>',
							customer_email		: '<?php echo $customer_email; ?>'
						},
				onLoading	: function(transport){
						
						//show progress loader
						$('progress-image-loader-'+parent_id).show();
							
				},
				onSuccess	: function(transport) {
					
						//hide progress loader
						//$('progress-image-loader-'+parent_id).hide();
						
						//hide the form
						//$('js-plugin-reply-form-wraper'+parent_id).hide();
						
						//display new thread
						//showNewAjaxThread('testimonial-thread-container'+parent_id,parseInt(transport.responseText));
						window.location.reload();
				}
				
		});
		
		
	}


	function submitAjaxThreadCommentReply(parent_id){
		
		//form validation 
		if($('thread-customer-reply-text-'+parent_id).getValue() == '' || $('thread-customer-reply-text-'+parent_id).getValue() == "What's on your mind"){
			
			alert('<?php echo __('The comment field is required') ?>');
			return false;
		}
		
		var url = '<?php echo $this->getUrl('prodfaqs/index/commentreply') ?>';
		
		new Ajax.Request(url, {
				
				method		: 'post',
				parameters	: {
							parent_faq_id	: parent_id,
							reply_comments		: $('thread-customer-reply-text-'+parent_id).getValue(),
							customer_name		: '<?php echo $customer_name; ?>',
							customer_email		: '<?php echo $customer_email; ?>'
						},
				onLoading	: function(transport){
						
						//show progress loader
						$('thread-progress-image-loader-'+parent_id).show();
							
				},
				onSuccess	: function(transport) {
						
						//hide progress loader
						//$('thread-progress-image-loader-'+parent_id).hide();
						
						//hide the form
						//$('thread-js-plugin-reply-form-wraper'+parent_id).hide();
						
						//display new thread
						//showNewAjaxThread('testimonial-thread-thread-'+parent_id,parseInt(transport.responseText));
						window.location.reload();
				}
				
		});
		
		
	}


</script>

<?php endif; ?>
<!--Reply JS ENDS-->



<?php
	$current_theme = Mage::getStoreConfig('prodfaqs/themes/select_theme');
	if($current_theme == ''){
			
			$current_theme = 'theme1';
	}	
?>

<?php if($current_theme == 'theme1' || $current_theme == 'theme3' || $current_theme == 'theme4'):?> <style type="text/css">.rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/prodfaqs/rating.png'); ?>") !important; </style> <?php endif; ?>

<?php if($current_theme == 'theme2' || $current_theme == 'theme5'): ?>
<style type="text/css">
.thread_rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/prodfaqs/rating2.png'); ?>") !important; }
.rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/prodfaqs/rating2.png'); ?>") !important; }
	
</style>
<?php endif; ?>


<?php if(Mage::helper('prodfaqs')->isProductFaqsAccordionEnable()) : ?>

<script type="text/javascript">
	
	Event.observe(window, 'load', function() {
		
		var default_accor_open = $('default_accordion_opened');
		if(default_accor_open != undefined){
			new Accordion('accordion-container',default_accor_open.title);
		}else{
				accordian = new Accordion('accordion-container',1);
		}
	});
	
</script>

<?php endif; ?>



<?php $current_faqs_product = Mage::registry('current_faqs_product'); ?>

	<div class="page-title category-title">
		<h1><?php echo $this->__('Questions on '.$current_faqs_product->getName()); ?></h1>
	</div>
	
	
<div id="product-next-page-wrapper">	


<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
	
	<div class="success-msg" id="rating-success" style="display:none;"><p id="rating_message"></p></div>
	<div class="error-msg" id="rating-fail" style="display:none;"><p id="rating_message"></p></div>
	
	
<?php if (!isset($faqs[0]['faqs_id'])) : ?>
	<p><?php echo $this->__('No Faqs Found !'); ?></p>
<?php else : ?>
    <div class="<?php echo $current_theme; ?>" id="accordion-container">
	
	<ul>
		<?php $i=0; $has_default_opened = '';
		
		foreach ($faqs as $_faqs): $i++; ?>
		<li>	
		
			<?php if($_faqs['accordion_opened'] == 1 && $has_default_opened == ''):  ?>
					<span id="default_accordion_opened" title="<?php echo $i; ?>" style="display:none;">
						<?php $has_default_opened = 'yes'; ?>
					</span>
			<?php endif; ?>
							
			<div class="accordion-toggle"><?php echo $_faqs["title"]; ?></div>
			<div class="accordion-content">
				
				<div class="answer"><?php echo Mage::helper('cms')->getPageTemplateProcessor()->filter($_faqs["faq_answar"]); ?></div>
		
				<?php if(Mage::helper('prodfaqs')->isProductFaqsRatingEnable()) : ?>
					<div class="rating_dv">											
						<span id="<?php echo 'faq_id_'.$i; ?>" style="display:none;" title="<?php echo $_faqs['faqs_id']; ?>" ></span>
						<span id="<?php echo 'stars_'.$i; ?>" style="display:none;" title="<?php echo $_faqs['rating_stars']; ?>" ></span>
						
						<div class="helpful">
						
							<span class="helpful-text" ><?php echo $this->__('How much this was helpful ') ?></span>
							
							<?php if($allowed_rating_customers == 'all' || ($allowed_rating_customers == 'registered' && Mage::helper('customer')->isLoggedIn())): ?>
					
								<?php if(in_array($_faqs['faqs_id'],$faqs_already_rated)): ?>	
										<span id="<?php echo 'has_rated_'.$i; ?>" style="display:none;" title="yes" ></span>
								<?php else: ?>
										<span id="<?php echo 'has_rated_'.$i; ?>" style="display:none;" title="no" ></span>
								<?php endif; ?>
								
							<?php else: ?>
							
								<span id="<?php echo 'has_rated_'.$i; ?>" style="display:none;" title="yes" ></span>
								
							<?php endif; ?>						
							
															
							<div id="<?php echo 'rating_'.$i; ?>" class="rating_container" style="float:right;"> </div>
						</div>
						<br class="clear" />
					</div>
				<?php endif; ?>
				
				<!-- LIKE / UNLIKE STARTS-->
					<?php if(Mage::helper('customer')->isLoggedIn() && Mage::helper('prodfaqs')->isProductFaqLikeEnable()): ?>
					
						<div class="like_dv" id="<?php echo 'like_container_'.$i; ?>">
								<?php //check customer alrady has liked
								    
								    $like_customer_ids = $_faqs['faq_like'];
								    $like_customer_ids_arr = explode(',',$like_customer_ids);
								    
								if(in_array($customer_id,$like_customer_ids_arr)){  ?>	
									
									<a href="javascript:" id="<?php echo 'like_element_'.$i; ?>"><?php echo $this->__('Unlike') ?></a>
									<?php if(Mage::getStoreConfig('prodfaqs/product_page/reply')): ?><a class="js-plugin-reply-button" href="javascript: showJsCommentForm('<?php echo 'js-plugin-reply-form-wraper'.$_faqs['faqs_id']; ?>',<?php echo $_faqs['faqs_id'] ?>)" id="<?php echo 'reply_element_'.$i; ?>" ><?php echo $this->__('Reply') ?></a><?php endif; ?>									
									<br />
									<div style="float:left;" id="<?php echo 'likeby_text_'.$i; ?>"><?php echo $this->__('Liked by '); ?></div>
									<div id="<?php echo 'like_result_'.$i; ?>"  class="like_on"><?php echo $this->__($customer_thumb.'You'); ?></div>				    
									
									<span id="<?php echo 'like_faq_id_'.$i; ?>" style="display:none;" title="<?php echo $_faqs['faqs_id']; ?>" ></span>
									<span id="<?php echo 'count_elements_'.$i; ?>" title="<?php if($like_customer_ids!= ''){ echo count($like_customer_ids_arr); }else{ echo 0; } ?>" style="display:none;" ><?php echo count($like_customer_ids_arr);?></span>
								    
								    
								<?php }else{    ?>			
							    
								    
									
									<a href="javascript:" id="<?php echo 'like_element_'.$i; ?>"><?php echo $this->__('Like') ?></a>
									<?php if(Mage::getStoreConfig('prodfaqs/product_page/reply')): ?><a class="js-plugin-reply-button" href="javascript: showJsCommentForm('<?php echo 'js-plugin-reply-form-wraper'.$_faqs['faqs_id']; ?>',<?php echo $_faqs['faqs_id'] ?>)" id="<?php echo 'reply_element_'.$i; ?>" ><?php echo $this->__('Reply') ?></a><?php endif; ?>
									<br />																					
									<div style="float:left;">
									    <div style="float:left;" id="<?php echo 'likeby_text_'.$i; ?>"><?php if($like_customer_ids != '') echo $this->__('Liked by '); ?></div>
									    <div id="<?php echo 'like_result_'.$i; ?>"></div>
									</div>
													    
									<span id="<?php echo 'like_faq_id_'.$i; ?>" style="display:none;" title="<?php echo $_faqs['faqs_id']; ?>" ></span>
									<span id="<?php echo 'count_elements_'.$i; ?>" title="<?php if($like_customer_ids!= ''){ echo count($like_customer_ids_arr); }else{ echo 0; } ?>" ></span>
								    
								
								<?php } ?>
							
							    
								
								<?php foreach($like_customer_ids_arr as $c_id): ?>
								    
									<?php  $customer_data = Mage::getModel('customer/customer')->load($c_id);
									
									if($c_id != '' && $c_id != $customer_id) { ?>
								    
									    <div class="like-customers-view"><?php echo $customer_thumb.$customer_data->getFirstname(); ?></div>
									
									
									<?php } ?>	
								    
								
								<?php endforeach; ?>
								
								
							
						</div>
					<?php endif; ?>
					<!-- LIKE / UNLIKE ENDS-->
					
					
					<!--REPLY STARTS-->
					
					<?php if(Mage::getStoreConfig('prodfaqs/product_page/reply') && !Mage::helper('prodfaqs')->isProductFaqLikeEnable() && Mage::helper('customer')->isLoggedIn()): ?>
						<div class="like_dv"><a class="js-plugin-reply-button" href="javascript: showJsCommentForm('<?php echo 'js-plugin-reply-form-wraper'.$_faqs['faqs_id']; ?>',<?php echo $_faqs['faqs_id'] ?>)" id="<?php echo 'reply_element_'.$i; ?>" style="padding-left:0;" ><?php echo $this->__('Reply') ?></a><br /></div>
					<?php endif; ?>
					
					
						<div class="clear"></div>

						<div class="js-plugin-reply-form-wrapper" id="<?php echo 'js-plugin-reply-form-wraper'.$_faqs['faqs_id'];?>" style="display:none;">
						<form action="" id="replyForm" name="replyForm" method="post" enctype="multipart/form-data">
						
							<div class="js-plugin-reply-customer-info">
								<img src="<?php echo $this->getJsUrl('prodfaqs/like/dman.png'); ?>" class="js-plugin-customer-thumb" />
								<div class="js-plugin-detail">
									<h3> <?php echo $customer_name; ?> </h3>
									
									<p> <?php echo $this->__('Add a reply') ?> </p>
								</div>
							</div>							
							<div class="js-plugin-reply-reply-filed">
								<textarea cols="32" rows="6" name="customer-reply-text" id="<?php echo 'customer-reply-text-'.$_faqs['faqs_id'] ?>" class="" ></textarea>
							</div>							
							<div class="js-plugin-reply-customer-form-footer">
								
								<img class="progress-image" id="<?php echo 'progress-image-loader-'.$_faqs['faqs_id'] ?>" title="Loading ..." alt="Loading ..." src="<?php echo $this->getSkinUrl('images/prodfaqs/loader.gif') ?>" >
								<button class="button" title="Post reply" type="button" onclick="javascript: submitAjaxCommentReply('<?php echo $_faqs['faqs_id'] ?>')">
									<span><span><?php echo $this->__('Post') ?></span></span>
								</button>								
								<a href="javascript: " onclick="$('<?php echo 'js-plugin-reply-form-wraper'.$_faqs['faqs_id']; ?>').hide()"> <?php echo $this->__('Cancel') ?></a>
							</div>
							
						</form>
						
						<div class="clear"></div>
						</div>
					
					<div class='testimonial-thread-container' id="<?php echo 'testimonial-thread-container'.$_faqs['faqs_id'] ?>">
						<?php $this->getThreads($_faqs['faqs_id']); ?>
						<div class="clear"></div>
					</div>
					<!--REPLY ENDS-->
					
					
					
					
			</div>
		
		
		
		</li>	
		<?php endforeach; ?>
	</ul>
	
    </div>
<?php endif; ?>



<?php if(Mage::helper('prodfaqs')->isProductFaqsAskQuestionEnable()): ?>

	<?php if(Mage::getStoreConfig('prodfaqs/product_ask/allow_customers') == 'all' || (Mage::getStoreConfig('prodfaqs/product_ask/allow_customers') == 'registered' && Mage::helper('customer')->isLoggedIn())): ?>
	
		
		<div class="ask-question-form" id="fme-ask-question-form-wraper" >
	
		<form action="<?php echo Mage::getUrl('prodfaqs/index/save'); ?>" id="fme-ask-question-form" name="fme-ask-question-form" method="post" enctype="multipart/form-data">
			
			
			<input name="status" id="status" value="0" type="hidden"  />
			<input name="links[relatedfaqs]" id="links[relatedfaqs]" value="<?php echo Mage::registry('current_faqs_product')->getId(); ?>" type="hidden"  />
			<input name="question_type" id="question_type" value="product_question" type="hidden"  />
			
			<div class="fieldset">
				<h2 class="legend"><?php echo $this->__('Ask a Question') ?></h2>
				
				<div class="success-msg" id="fme-faq-success" style="display:none;"><p id="fme-faq_success_message"></p></div>
				<div class="error-msg" id="fme-faq-fail" style="display:none;"><p id="fme-faq_fail_message"></p></div>
				
				
				<ul class="form-list">
					<li class="fields">
						<div class="field">
						    <label for="customer_name"  class="required"><em>*</em><?php echo $this->__('Name') ?></label>
						    <div class="input-box">
							    <input name="customer_name" id="customer_name" title="<?php echo $this->__('Customer Name ') ?>" value="<?php echo Mage::helper('customer')->getCustomerName(); ?>" class="required-entry input-text" type="text" />
						    </div>
						</div>
					
						<div class="field">
						    <label for="customer_email"  class="required"><em>*</em><?php echo $this->__('Email') ?></label>
						    <div class="input-box">
							<input name="customer_email" id="customer_email" title="<?php echo $this->__('Customer Email') ?>" value="<?php echo Mage::helper('customer')->getCustomer()->getEmail(); ?>" class="required-entry validate-email input-text" type="text" />
						    </div>
						</div>
					</li>
					<li class="fields">
						<div class="field">
						    <label for="visibility"  class="required"><em>*</em><?php echo $this->__('Visibility') ?></label>
						    <div class="input-box">
							<select name="visibility" id="visibility" title="<?php echo $this->__('Visibility') ?>" class="required-entry input-text" >
								<option value="public"><?php echo $this->__('Public'); ?></option>
								<option value="private"><?php echo $this->__('Private'); ?></option>
							</select>
						    </div>
						</div>
					</li>					
					<li class="wide">
						<label for="title" class="required"><em>*</em><?php echo $this->__('Question') ?></label>
						<div class="input-box">
						    <textarea name="title" id="title" title="<?php echo $this->__('Question') ?>" class="required-entry input-text" cols="3" rows="2"></textarea>
						</div>
					</li>
					
					
					<?php if(Mage::helper('prodfaqs')->isCaptchaEnable()): ?>
					
						<script type="text/javascript">
							var RecaptchaOptions = {
								tabindex: 1,
								theme: "clean"
							};
						</script>
						
					<li class="wide"> 
						
						
						<?php $recaptcha_path = Mage::getModuleDir('Helper','FME_Prodfaqs'); ?>
						<?php require_once($recaptcha_path."/Helper/recaptchalib.php"); ?>
						
						
						
						<?php $publickey = Mage::helper('prodfaqs')->getCaptchaApiPublicKey(); ?>
						<?php $privatekey = Mage::helper('prodfaqs')->getCaptchaApiPrivateKey(); ?>
						
						<?php
						
						if($publickey != '' && $privatekey != ''):
							echo recaptcha_get_html($publickey);
						else:
							echo 'Please include the <a href="https://www.google.com/recaptcha/admin/create" target="blank">Google Captcha API keys</a>';
						endif;
						
						?>					
						
					</li>
					<?php endif; ?>
				</ul>
			
			
				
					<br />
					<p id="progress_loader"><img title="<?php echo $this->__('Processing ...') ?>" src="<?php echo $this->getSkinUrl('images/prodfaqs/loader.gif')?>" /></p>
					
							
					<button  onclick="saveQuestionForm()"  type="button" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				    
				
			
			</div>
			<div class="clear"></div>
			
		</form>
		
		</div>

	<?php endif; ?>
	
<?php endif; ?>

	<a href="<?php echo $current_faqs_product->getProductUrl(); ?>" class="faq-back-link" title="<?php echo $this->__('Back to the product page'); ?>" >
		<?php echo $this->__('Back to the product page'); ?>
	</a>

	<script type="text/javascript">
   
		//form posting
	    
		function saveQuestionForm(){	    
		    
		    var fmefaqForm = new VarienForm('fme-ask-question-form', true);
		    
		    
		    
		    
		     //if the form is valid
		    if(fmefaqForm.validator.validate()) {
			
			$('fme-ask-question-form').request({
				    
				    method: 'post',
				    onLoading:function(transport){
					
					    $('progress_loader').setStyle({display:'block'});
					    
					},
				    onSuccess: function(transport){
					    alert(transport.responseText);
					    $('progress_loader').setStyle({display:'none'});				      
					    
					},
				    onFailure: function(transport){
					   alert(transport.responseText);
					   $('progress_loader').setStyle({display:'none'});
					    
				    }
				    
				});
				  
			}
			
			
		    }
	    
	    
	</script>




</div>