<?php
/**
 * FAQs And Product Questions
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   FME
 * @package    FAQs And Product Questions
 * @author     Asif Hussain <support@fmeextensions.com>
 * 	       
 * @copyright  Copyright 2012 © www.fmeextensions.com All right reserved
 */
?>



<?php 

if(Mage::getStoreConfig('prodfaqs/list/display_categories') == 'selected'):

	$topics = $this->getSelectedTopics();
else :
	$topics = $this->getTopics();
endif;

$num_of_question_to_display = Mage::getStoreConfig('prodfaqs/list/show_number_of_questions');

$cat_num = count($topics);

$faq_num = $num_of_question_to_display;

$allowed_rating_customers = Mage::getStoreConfig('prodfaqs/rating/allow_customers');

//Faqs that already has been rated, in that session
$faqs_already_rated = Mage::getSingleton('customer/session')->getRatedFaqsId();


?>

<?php if(Mage::getStoreConfig('prodfaqs/rating/enable')) : ?>
		<script type="text/javascript">		
		jQuery.noConflict();
			Event.observe(window, 'load', function() {
				var cat = '<?= $cat_num; ?>';
				var faq = '<?= $faq_num; ?>';
				//var is_rated = '<?= $is_rated; ?>';
				
				for(c=1; c<=cat; c++ ){
					
					for(f=1; f<=faq; f++){
						
						var rating_element = $('rating_'+c+'_'+f);
						if($('has_rated_'+c+'_'+f) != undefined){
							var is_rated = $('has_rated_'+c+'_'+f).readAttribute('title');
							if(is_rated == 'yes') is_rated = true;
							else if(is_rated == 'no') is_rated = false;
						}
						if(rating_element != undefined){
							
							rating = new Control.Rating(rating_element,
								{
									rated: is_rated,
									value: parseFloat($('stars_'+c+'_'+f).readAttribute('title')),
									cat_id: parseInt($('cat_id_'+c+'_'+f).readAttribute('title')),
									faq_id: parseInt($('faq_id_'+c+'_'+f).readAttribute('title')),
									updateUrl:'<?php echo $this->getUrl('*/*/rating') ?>',
									updateOptions : {
										method: 'post',
										onSuccess: function(transport) {
												$('rating-success').appear();
												$('rating_message').update(transport.responseText);
											},
										onFailure: function(transport) {
												$('rating-fail').appear();
												$('rating_message').update(transport.responseText);
											}
										}
								});
						}			
					}		
				}	
			});
		</script>

<?php endif; ?>



<?php

// like/unlike
$t_session = Mage::getSingleton('customer/session');
if($t_session->isLoggedIn()){
    
    $customer = $t_session->getCustomer();
    $customer_name = $customer->getFirstname();
    $customer_id = $customer->getId();
    
    $customer_thumb_path = $this->getJsUrl('prodfaqs/like/dman.png'); 
    $customer_thumb = "<img src='$customer_thumb_path' style='width:15px; height:15px; margin:0 5px;'>";

}

?>

<?php if(Mage::helper('customer')->isLoggedIn() && Mage::helper('prodfaqs')->isGeneralFaqLikeEnable()): ?>

<script type="text/javascript">
	
    Event.observe(window, 'load', function() {
		
		var cat = '<?= $cat_num; ?>';
		var faq = '<?= $faq_num; ?>';
		var customer_name = '<?= $customer_name; ?>';
		var customer_id = '<?= $customer_id; ?>';
		
		for(k=1; k<=cat; k++){
			
			for(f=1; f<=faq; f++){
			    
			    if($('like_faq_id_'+k+'_'+f) != undefined){
				
				like = new Control.Like($('like_container_'+k+'_'+f),$('like_element_'+k+'_'+f),$('like_result_'+k+'_'+f),$('likeby_text_'+k+'_'+f),$('count_elements_'+k+'_'+f),
					{
					    likeby_name		: customer_name,
					    likeby_id 		: customer_id,
					    liked_obj_id 	: parseInt($('like_faq_id_'+k+'_'+f).readAttribute('title')),
					    likeby_avatar 	: '<?php echo $customer_thumb_path; ?>',
					    updateUrl		:'<?php echo $this->getUrl('prodfaqs/index/like') ?>',
					    updateOptions 	: {					
								    method:'post',
								    onSuccess: function(transport) {}
								   }
					    
					});
				
			    }
			    
			}
		}
	
    });

</script>

<?php endif; ?>




<?php
	$current_theme = Mage::getStoreConfig('prodfaqs/themes/select_theme');
	if($current_theme == ''){
			
			$current_theme = 'theme1';
	}
	
?>

<?php if($current_theme == 'theme1' || $current_theme == 'theme3' || $current_theme == 'theme4'):?> <style type="text/css">.rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/prodfaqs/rating.png'); ?>") !important; </style> <?php endif; ?>

<?php if($current_theme == 'theme2' || $current_theme == 'theme5'):?> <style type="text/css">.rating_container a { background-image: url("<?php echo $this->getSkinUrl('images/prodfaqs/rating2.png'); ?>") !important; </style> <?php endif; ?>



<?php if(Mage::getStoreConfig('prodfaqs/list/enable_accordion')) : ?>

<script type="text/javascript">
	
	Event.observe(window, 'load', function() {
		
		var cat = '<?= $cat_num; ?>';
		
		
		for(c=1; c<=cat; c++ ){
			
			var accor_element = $('faq_accordian_'+c);
			var default_accor_open = $('default_accordion_opened_category_'+c);
			if(default_accor_open != undefined){
				accordian = new Accordion(accor_element,default_accor_open.title)
			}else{
				accordian = new Accordion(accor_element,1)
			}
		}
	});
	
</script>

<?php endif; ?>



<div id="wrapper">



<div class="page-title">
	<h1>
		
		<?php
			if(Mage::getStoreConfig('prodfaqs/list/page_title') != '')
				
				echo Mage::getStoreConfig('prodfaqs/list/page_title');
			else
				echo Mage::helper('prodfaqs')->__('FAQ\'s Categories');
		?>
	</h1>
</div>

	<div class="success-msg" id="rating-success" style="display:none;"><p id="rating_message"></p></div>
	<div class="error-msg" id="rating-fail" style="display:none;"><p id="rating_message"></p></div>
	
	

<?php if ( count($topics) == 0 ) : ?>    
		<p class="empty"><?php echo Mage::helper('prodfaqs')->__('No Category find yet!') ?></p>
<?php else : ?>

	<?php $cat = 0; foreach ($topics as $_topic): $cat++; ?>
	
		
		
		
		<div class="<?php echo $current_theme; ?>" id="<?php echo 'faq_accordian_'.$cat; ?>">
					
			<h1><a href="<?php echo Mage::helper('prodfaqs')->getUrl($_topic['identifier']); ?>"><?php echo $_topic["title"]; ?></a></h1>
					
			<?php $faqs = $this->getFaqsOfTopics($_topic['topic_id']); ?>
					
			<?php if( count($faqs) == 0 ): ?>
			
				<p class="empty"><?php echo Mage::helper('prodfaqs')->__('No Questions found in this catagory yet!') ?></p>
							
			<?php else: ?>
							
				<ul>		
					<?php $i=0; $has_default_opened = '';
					
					foreach($faqs as $f_val): $i++; ?>
									
							
							<?php if($f_val['accordion_opened'] == 1 && $has_default_opened == ''):  ?>
								<span id="<?php echo 'default_accordion_opened_category_'.$cat; ?>" title="<?php echo $i; ?>" style="display:none;">
									<?php $has_default_opened = 'yes'; ?>
								</span>
							<?php endif; ?>
						
						
							<?php if($i <= $num_of_question_to_display): ?>
								<li>		
								
									<div class="accordion-toggle" ><?php echo $f_val['title']; ?></div>
									<div class="accordion-content">
										
		
										<div class="answer"><?php echo Mage::helper('cms')->getPageTemplateProcessor()->filter($f_val['faq_answar']); ?></div>
											
											
										<?php if(Mage::getStoreConfig('prodfaqs/rating/enable')) : ?>
												
											<div class="rating_dv">											
												<span id="<?php echo 'cat_id_'.$cat.'_'.$i; ?>" style="display:none;" title="<?php echo $_topic['topic_id'] ?>"></span>
												<span id="<?php echo 'faq_id_'.$cat.'_'.$i; ?>" style="display:none;" title="<?php echo $f_val['faqs_id']; ?>" ></span>
												<span id="<?php echo 'stars_'.$cat.'_'.$i; ?>" style="display:none;" title="<?php echo $f_val['rating_stars']; ?>" ></span>
												<div class="helpful">
													
													<span class="helpful-text" ><?php echo $this->__('How helpful was this? ') ?></span>
													
													<?php if($allowed_rating_customers == 'all' || ($allowed_rating_customers == 'registered' && Mage::helper('customer')->isLoggedIn())): ?>
					
														<?php if(in_array($f_val['faqs_id'],$faqs_already_rated)): ?>	
																<span id="<?php echo 'has_rated_'.$cat.'_'.$i; ?>" style="display:none;" title="yes" ></span>
														<?php else: ?>
																<span id="<?php echo 'has_rated_'.$cat.'_'.$i; ?>" style="display:none;" title="no" ></span>
														<?php endif; ?>
														
													<?php else: ?>
													
														<span id="<?php echo 'has_rated_'.$cat.'_'.$i; ?>" style="display:none;" title="yes" ></span>
														
													<?php endif; ?>													
													
													<div id="<?php echo 'rating_'.$cat.'_'.$i; ?>" class="rating_container" style="float:right;"> </div>
												
												</div>
												<br class="clear" />
											</div>
												
										<?php endif; ?>
										
										<!-- LIKE / UNLIKE STARTS-->
										<?php if(Mage::helper('customer')->isLoggedIn() && Mage::helper('prodfaqs')->isGeneralFaqLikeEnable()): ?>
										
											<div class="like_dv" id="<?php echo 'like_container_'.$cat.'_'.$i; ?>">
													<?php //check customer alrady has liked
													    
													    $like_customer_ids = $f_val['faq_like'];
													    $like_customer_ids_arr = explode(',',$like_customer_ids);
													    
													if(in_array($customer_id,$like_customer_ids_arr)){  ?>	
														
														<a href="javascript:" id="<?php echo 'like_element_'.$cat.'_'.$i; ?>"><?php echo $this->__('Unlike') ?></a><br />
														<div style="float:left;" id="<?php echo 'likeby_text_'.$cat.'_'.$i; ?>"><?php echo $this->__('Liked by '); ?></div>
														<div id="<?php echo 'like_result_'.$cat.'_'.$i; ?>"  class="like_on"><?php echo $this->__($customer_thumb.'You'); ?></div>				    
														
														<span id="<?php echo 'like_faq_id_'.$cat.'_'.$i; ?>" style="display:none;" title="<?php echo $f_val['faqs_id']; ?>" ></span>
														<span id="<?php echo 'count_elements_'.$cat.'_'.$i; ?>" title="<?php if($like_customer_ids!= ''){ echo count($like_customer_ids_arr); }else{ echo 0; } ?>" style="display:none;" ><?php echo count($like_customer_ids_arr);?></span>
													    
													    
													<?php }else{    ?>			
												    
													    
														
														<a href="javascript:" id="<?php echo 'like_element_'.$cat.'_'.$i; ?>"><?php echo $this->__('Like') ?></a><br />
														<div style="float:left;">
														    <div style="float:left;" id="<?php echo 'likeby_text_'.$cat.'_'.$i; ?>"><?php if($like_customer_ids != '') echo $this->__('Liked by '); ?></div>
														    <div id="<?php echo 'like_result_'.$cat.'_'.$i; ?>"></div>
														</div>
																		    
														<span id="<?php echo 'like_faq_id_'.$cat.'_'.$i; ?>" style="display:none;" title="<?php echo $f_val['faqs_id']; ?>" ></span>
														<span id="<?php echo 'count_elements_'.$cat.'_'.$i; ?>" title="<?php if($like_customer_ids!= ''){ echo count($like_customer_ids_arr); }else{ echo 0; } ?>" ></span>
													    
													
													<?php } ?>
												
												    
													
													<?php foreach($like_customer_ids_arr as $c_id): ?>
													    
														<?php  $customer_data = Mage::getModel('customer/customer')->load($c_id);
														
														if($c_id != '' && $c_id != $customer_id) { ?>
													    
														    <div class="like-customers-view"><?php echo $customer_thumb.$customer_data->getFirstname(); ?></div>
														
														
														<?php } ?>	
													    
													
													<?php endforeach; ?>
													
													
												    
												
											</div>
										<?php endif; ?>
										<!-- LIKE / UNLIKE ENDS-->
									</div>
								</li>	
							<?php endif; ?>
							
					<?php endforeach; ?>
				</ul>
							
			<?php endif; ?>
						
			<?php if(Mage::getStoreConfig('prodfaqs/list/enable_view_more') == 1 &&  count($faqs) > $num_of_question_to_display && $num_of_question_to_display!= 0 ): ?>
					
				<a class="read_more" href="<?php echo Mage::helper('prodfaqs')->getUrl($_topic['identifier']); ?>"><?php echo $this->__('Read more'); ?></a>
				
			<?php endif; ?>
		
		</div>
				
	<?php endforeach; ?>	
	
	
<?php endif; ?>


 <!-- Custom Code -->

	<!--Question Form Starts-->
	<?php //if(Mage::helper('prodfaqs')->isProductFaqsAskQuestionEnable()):
		$topicsDropDown = $this->getTopics();
		$NTopics = '';
		foreach ($topicsDropDown as $ts) {
			$NTopics .= '<option value='.$ts['topic_id'].'>'.$ts['title'].'</option>';
		}
	?> 
	
	<div class="ask-question-form" id="fme-ask-question-form-wraper" style="display: none">
	
		<form action="<?php echo Mage::getUrl('prodfaqs/index/savegeneral'); ?>" id="fme-ask-question-form" name="fme-ask-question-form" method="post" enctype="multipart/form-data">
			
			<input name="status" id="status" value="0" type="hidden"  />
			<input name="question_type" id="question_type" value="general_question" type="hidden"  />
			
			<div class="fieldset">
				<h2 class="legend"><?php echo $this->__('Please complete the form below.') ?></h2>
				<ul class="form-list">
					<li class="fields">
					    
						<div class="field">
						    <label for="customer_name"  class="required"><em>*</em><?php echo $this->__('Name') ?></label>
						    <div class="input-box">
							<input name="customer_name" id="customer_name" title="<?php echo $this->__('Customer Name ') ?>" value="<?php echo Mage::helper('customer')->getCustomerName(); ?>" class="required-entry input-text" type="text" />
						    </div>
						</div>
						
						<div class="field">
						    <label for="customer_email"  class="required"><em>*</em><?php echo $this->__('Email') ?></label>
						    <div class="input-box">
							<input name="customer_email" id="customer_email" title="<?php echo $this->__('Customer Email') ?>" value="<?php echo Mage::helper('customer')->getCustomer()->getEmail(); ?>" class="required-entry validate-email input-text" type="text" />
						    </div>
						</div>
					    
					</li>
					<li class="fields">
						<div class="field">
						    <label for="visibility"  class="required"><em>*</em><?php echo $this->__('Visibility') ?></label>
						    <div class="input-box">
							<select name="visibility" id="visibility" title="<?php echo $this->__('Visibility') ?>" class="required-entry input-text" >
								<option value="private"><?php echo $this->__('Private'); ?></option>
								<option value="public"><?php echo $this->__('Public'); ?></option>
							
							</select>
						    </div>
						</div>
						
						<div class="field">
						    <label for="topic_id" ></label><?php echo $this->__('Select Topic') ?></label>
						    <div class="input-box">
							<select name="topic_id" id="topic_id" title="<?php echo $this->__('Select Topic') ?>" class="input-text" >
								<?php echo $NTopics; ?>
							</select>
						    </div>
						</div>
					</li>	

					<li class="fields">
						<div class="field">
						    <label for="telephone"  class="required"><?php echo $this->__('Telephone:') ?></label>
						    <div class="input-box">
							<input name="telephone" id="telephone" title="<?php echo $this->__('Customer Telephone #') ?>" class="input-text" type="text" />
						    </div>
						</div>
					</li>


					<li class="wide">
						<label for="title" class="required"><em>*</em><?php echo $this->__('Question') ?></label>
						<div class="input-box">
						    <textarea name="title" id="title" title="<?php echo $this->__('Question') ?>" class="required-entry input-text" cols="3" rows="2"></textarea>
						</div>
					</li>
					
					
					<?php if(Mage::helper('prodfaqs')->isCaptchaEnable()): ?>
					
						<script type="text/javascript">
							var RecaptchaOptions = {
								tabindex: 1,
								theme: "clean"
							};
						</script>
					
					<li class="wide">
						
						<?php $recaptcha_path = Mage::getModuleDir('Helper','FME_Prodfaqs'); ?>
						<?php require_once($recaptcha_path."/Helper/recaptchalib.php"); ?>
						
						<?php $publickey = Mage::helper('prodfaqs')->getCaptchaApiPublicKey(); ?>
						<?php $privatekey = Mage::helper('prodfaqs')->getCaptchaApiPrivateKey(); ?>
						
						<?php
						
						if($publickey != '' && $privatekey != ''):
							echo recaptcha_get_html($publickey);
						else:
							echo 'Please include the <a href="https://www.google.com/recaptcha/admin/create" target="blank">Google Captcha API keys</a>';
						endif;
						
						?>
						
						
					</li>
					<?php endif; ?>
				</ul>
			
			
				
					<br />
					<p id="progress_loader"><img src="<?php echo $this->getSkinUrl('images/prodfaqs/loader.gif')?>" /></p>
					
							
					<button  type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
					
				
			
			</div>
			<div class="clear"></div>
			
		</form>
		
	</div>

	<!--Question Form Ends-->
	
		<?php if(Mage::getStoreConfig('prodfaqs/product_ask/allow_customers') == 'all' || (Mage::getStoreConfig('prodfaqs/product_ask/allow_customers') == 'registered' && Mage::helper('customer')->isLoggedIn())): ?>
			<?php if(Mage::helper('prodfaqs')->getProductFaqsFormOpen() == 'slide'): ?>
				<script type='text/javascript'>	    
					function SDEffect(element){   new Effect.SlideDown(element, {duration:0.1}); $('fme-faq-btn-slide-close').show(); $('fme-faq-btn-slide-close').setStyle({background: "url('<?php echo $this->getSkinUrl('images/prodfaqs/white-arrow-prod.gif') ?>') no-repeat scroll 0 0 transparent" }); $('fme-faq-btn-slide-open').hide(); $('faqsaddslide-wraper').setStyle({marginTop: "-28px" }); }
					function SUEffect(element){   new Effect.SlideUp(element, {duration:0}); $('fme-faq-btn-slide-close').hide(); $('fme-faq-btn-slide-open').show();  $('faqsaddslide-wraper').setStyle({marginTop: "-16px" }); }
				</script>
				<p class="faqsaddslide" id="faqsaddslide-wraper">
					<a class="btn-slide" id="fme-faq-btn-slide-open" href="javascript:" onclick="SDEffect('fme-ask-question-form-wraper');" ><?php echo $this->__('Ask a Question'); ?></a>
					<a class="btn-slide" id="fme-faq-btn-slide-close" href="javascript:" onclick="SUEffect('fme-ask-question-form-wraper');" style="display:none;" ><?php echo $this->__('Ask a Question'); ?></a>
				</p>
			<?php else: ?>
				<p class="faqsaddslide" >
					<a class="btn-slide" title="<?php echo $this->__('Ask a Question') ?>" id="fme-faq-btn-slide-open" href="javascript:" onclick="Modalbox.show($('fme-ask-question-form-wraper'), {title: this.title, width: 700, height:615 }); return false;" ><?php echo $this->__('If you cannot find an answer to your questions. Click Here to Ask Us - We will get back to you with our advice'); ?></a>
				</p>
				
			<?php endif; ?>
			
		<?php endif; ?>
		
	<?php //endif ;?>
	
	<!-- End Custom Code -->


</div>
<script type="text/javascript">
    //< ![CDATA[
        var customForm = new VarienForm('fme-ask-question-form');
    //]]>
</script>