<?php $limit_length = 160;?>
<?php if (($_items_reviews = $this->getTopRatingProductCollection_Show()) && $_items_reviews->getSize()): ?>
<div class="widget widget-top-rating-products">
    <div class="widget-title">
        <h2><?php echo $this->__('Top Rating Products') ?></h2>
    </div>
    <div class="widget-products">
    <?php $_columnCount = $this->getColumnCount(); ?>
	<?php $i=0; foreach ( $_items_reviews as $_review) :?>
        <?php $_product = Mage::getModel('catalog/product')->load($_review['entity_pk_value']); ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85) ?>" width="85" height="85" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                       
						<?php echo ('Point: '.$_review['rating_summary']. ' / 100'); ?>
						
						<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
						 
                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>
                        <?php if ($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==count($_items_reviews)): ?>
        </ul>
        <?php endif ?>
        <?php endforeach; ?>
    </div>
</div>
<?php endif; ?>