
<div class="callback grass">
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="page-head title-grass">
    <h3><?php echo Mage::helper('quotes')->__('Astrostep Underlay Sample Request') ?></h3>
</div>
<form action="<?php echo Mage::getUrl('quotes/index/post') ?>" id="quoteForm" method="post">
<!--id of email -->
<input type="text" name="id" style="display:none" value="4" />
<!--------------->
<table style="width: 559px;" border="0" cellspacing="0" cellpadding="0">
<tbody>

<tr valign="TOP" height="65">

<td colspan="4">
<p><span class="style17">For more information and to request a sample of our Astrostep Underlay please complete the form below. (Please complete all <strong>Bold </strong>fields)</span></p>
</td>
</tr>
<tr>

<!--id of email -->


<!--------------->
<td valign="MIDDLE" width="90" height="25">
<p><span class="style16" style="font-weight: bold;">Name</span></p>
</td>
<td colspan="3" valign="MIDDLE">
<p><input type="text" name="name" id="name" size="37" onblur="this.value=this.value.toUpperCase()" class="required-entry"/></p>
<div id="sample_terrace_Name_errorloc" class="error_strings">&nbsp;</div>
</td>
</tr>
<tr>
<td valign="MIDDLE" height="25">
<p><span class="style16" style="font-weight: bold;">Address</span></p>
</td>
<td colspan="3" valign="MIDDLE">
<p><input type="text" name="address1" size="37" onblur="this.value=this.value.toUpperCase()" class="required-entry"/></p>
<div id="sample_terrace_Address_errorloc" class="error_strings">&nbsp;</div>
</td>
</tr>
<tr>
<td height="48">&nbsp;</td>
<td colspan="3" valign="top">
<p><input type="text" name="address2" size="37" onblur="this.value=this.value.toUpperCase()"/></p>
</td>
</tr>
<tr>
<td valign="MIDDLE" height="48">
<p>&nbsp;</p>
</td>
<td colspan="3" valign="MIDDLE">
<p><input type="text" name="address3" size="37" onblur="this.value=this.value.toUpperCase()"/></p>
</td>
</tr>
<tr>
<td valign="MIDDLE" height="25">
<p><span class="style16" style="font-weight: bold;">Postcode</span></p>
</td>
<td colspan="3" valign="MIDDLE">
<p><input type="text" name="postcode" size="20" onblur="this.value=this.value.toUpperCase()" class="required-entry"/></p>
<div id="sample_terrace_Postcode_errorloc" class="error_strings">&nbsp;</div>
</td>
</tr>
<tr>
<td valign="MIDDLE" height="48">
<p><span class="style16">Tel</span></p>
</td>
<td colspan="3" valign="MIDDLE">
<p><input type="text" name="tel" size="20" /></p>
</td>
</tr>
<tr>
<td valign="MIDDLE" height="26">
<p><span class="style16" style="font-weight: bold;">Email</span></p>
</td>
<td colspan="3" valign="MIDDLE">
<p><input type="text" name="email" size="37" class="required-entry input-text validate-email"/></p>
<div id="sample_terrace_email_errorloc" class="error_strings">&nbsp;</div>
</td>
</tr>
<tr>

<td valign="TOP" height="46">
<p><span class="style16" style="font-weight: bold;"> How did you hear about us? </span></p>
</td>
<td colspan="3" valign="top"><input id="How_did_you_hear_about_us" type="text" name="infor-from" size="37" />
<div id="sample_terrace_How_did_you_hear_about_us_errorloc" class="error_strings">&nbsp;</div>
</td>
</tr>
<tr>

</tr>
<!--<tr>
<td colspan="3" valign="MIDDLE" height="25">
<p><span class="style17">To be used for </span></p>
</td>
<td valign="top" width="432"><span class="style16"> <input type="text" name="To be used for" size="37" /> </span></td>
</tr>-->
<!--
<tr>
<td colspan="3" valign="TOP" height="113">
<p><span class="style17">Enquiry</span></p>
</td>
<td valign="TOP">
<p><textarea name="enquiry" rows="5" cols="37"></textarea></p>
</td>
</tr>-->
<tr>
<td colspan="1" valign="TOP" height="30"></td>
<td valign="TOP" >
<p><input type="hidden" name="subject" value="Astrostep Sample Request" /><input style="cursor:pointer"  type="SUBMIT" value="Submit" /></p>
</td>
</tr>
<tr>
<td colspan="4" valign="MIDDLE" height="30">
<p><span class="style17"><br /> <br /> </span></p>
</td>
</tr>
<tr>
<td height="1">&nbsp;</td>
<td width="12">&nbsp;</td>
<td width="8">&nbsp;</td>
<td>&nbsp;</td>
</tr>
</tbody>
</table>
</form>
<script type="text/javascript">
    var quoteForm = new VarienForm('quoteForm', true);
</script>
</div>