<?php
    $_products = $this->getProductCollection();
    $_columnCount = $this->getColumnCount();
    $count =  count($_products);
    
    $config = new EM_Em0059settings_Em0059settings();
    $w = $config->get_editor_pick_width();
    $h = $config->get_editor_pick_height();
    $bg = $config->get_editor_pick_bgcolor(); 
?>
<div class="editor-pick-home">
    <div class="widget-title">
        <h2><?php echo $this->__('Editor Pick') ?></h2>
    </div>
    <?php if ($count == 0): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <div id="content-editor-pick" class="editor-pick-content">        
        <div class="slideshow-box">
            <ul id="<?php if(count($_products) > $_columnCount):?>editor-pick-home-content<?php else:?>none-editor-pick-home-content<?php endif; ?>" class="jcarousel-skin-tango">                
                <?php $j=1; foreach ($_products->getItems() as $_product): ?>
                <?php
        					//$_product = Mage::getModel('catalog/product')->load($_item->getId());
                ?>
                <?php if($j%3 == 1 && $j <= $count): ?>
                <li>
                <div class="slide-item">
                <ul class="slide-item-list">
                <?php endif; ?>
                <li class="item<?php if($j % 3 == 1):?><?php echo $this->__(' first') ?><?php elseif(($j % 3 == 0) || $j == $count): ?><?php echo $this->__(' last') ?><?php endif; ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w, $h) ?>" width="<?php echo $w ?>" height="<?php echo $h ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                    <div class="product-shop">
                        <div class="f-fix">
                            <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>                            
                        </div>
                    </div>
                </li>
            <?php if(($j % 3) == 0 || $j == $count): ?>             
            </ul>            
            </div>            
            </li>
            <?php endif; ?>            
            <?php $j ++ ?>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
        <script type="text/javascript">
			jQuery(document).ready(function() {
				jQuery('#editor-pick-home-content').jcarousel({
				wrap: 'circular',
			auto:0,
			buttonNextHTML:'<a class="next" href="javascript:void(0);" title="Next">Next</a>',
			buttonPrevHTML:'<a class="previous" href="javascript:void(0);" title="Previous">Pre</a>',
			scroll:1,
			animation:'slow'
				});
			});
		</script>
    <?php endif; ?>
</div>
