<?php if(Mage::getStoreConfig('blog/comments_facebook/enabled')):?>
<div id="blog-fb-root"></div>
<script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/<?php echo Mage::app()->getLocale()->getDefaultLocale()?>/all.js#xfbml=1&appId=<?php echo Mage::getStoreConfig('blog/comments_facebook/app_id')?>";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<?php endif;?>