<?php
    $_products = $this->getProductCollection();
    $_columnCount = $this->getColumnCount();
    
    $config = new EM_Em0059settings_Em0059settings();
    $w = $config->get_tabs_width();
    $h = $config->get_tabs_height();
    $bg = $config->get_tabs_bgcolor();    
?>
<div class="new-arrival">
<?php if (count($_products) == 0): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="content-news-arrival" class="news-arrival-content">
    <div class="<?php if(count($_products) <= $_columnCount): ?>none-slider-new-arrival<?php else: ?>slideshow-box<?php endif ?>">
        <ul class="jcarousel-skin-tango">
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php
					//$_product = Mage::getModel('catalog/product')->load($_item->getId());
        ?>
            <li class="item<?php echo (++$i == count($_products))?' last':''; ?>">
                <?php 
        			$pId= $_product['entity_id'];									
        			$product = Mage::getModel('catalog/product')->load($pId);
    			?> 
    			<?php Mage::helper('productlabels')->display($product);?>
                
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($w, $h) ?>" width="<?php echo $w ?>" height="<?php echo $h ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" /></a>
                <div class="product-shop">
                    <div class="f-fix">
                        <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h3>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php echo $this->getPriceHtml($_product, true, '-widget-new-list') ?>                        
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery('#content-news-arrival > div.slideshow-box > ul').jcarousel({
        wrap: 'circular',
    auto:0,
    buttonNextHTML:'<a class="next" href="javascript:void(0);" title="Next">Next</a>',
    buttonPrevHTML:'<a class="previous" href="javascript:void(0);" title="Previous">Pre</a>',
    scroll:1,
    animation:'slow'
        });
    });
</script>
<?php endif; ?>
</div>